; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/mamun/Development/workspace/clj/zme/zme-web/src/crossover/template1.clj

(ns template1)

(defn get-data []
  {:a "1" :b "2"})
